version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8089:8080
      - 50009:50000
    container_name: my-jenkins-3
    volumes:
      - /Users/praveensingampalli/Documents/BOOTCAMP2_FINAL/docker/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

